@startuml
Class Orquesta{}
Class Tambor{}
Class Violin {}
Class Trombon {}
Class Clarinete{}
Orquesta "1" *--> "1" Violin
Orquesta"1" *--> "0..*" Tambor
Orquesta "1" *--> "1..5" Trombon
Orquesta "1" *--> "1..4" Clarinete
Trombon .. Clarinete: {or}
@enduml